<a href="https://colab.research.google.com/github/VIHAN-droid/AI-ML-PROJECT/blob/main/PYTORCH/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# USED FOR CALCULATING DIFFERENTITATION

In [2]:
import torch

In [26]:
# use floating pts for calculation diff
x = torch.tensor([3.0], requires_grad=True) # set it true whenever you want to calculate the differentitation
y = x**2
y.backward(retain_graph=True)  # calculates the differentitation ||  set retain graph to true if val of dy/dx can used afterwards like in dz/dx in next cell
x.grad  # shows the output after diff

tensor([6.])

In [27]:
z = torch.sin(y)
z.backward()
x.grad

tensor([0.5332])

In [38]:
x = torch.tensor([6.7])
y = torch.tensor([0.0])

In [40]:
w = torch.tensor([1.0], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

In [41]:
z = w*x + b
z

tensor([6.7000], grad_fn=<AddBackward0>)

In [42]:
y_pred = torch.sigmoid(z)
y_pred

tensor([0.9988], grad_fn=<SigmoidBackward0>)

In [43]:
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

loss = binary_cross_entropy_loss(y_pred,y)
loss

tensor([6.7012], grad_fn=<NegBackward0>)

In [44]:
loss.backward()
print(w.grad)
print(b.grad) # these are the coefficients

tensor([6.6918])
tensor([0.9988])


In [51]:
# if u run a grad in loop then its imp to clear the tensor having grad value otherwise it keeps getting added
# do -> x.grad.zero_()

x = torch.tensor([3.0],requires_grad=True)
for i in range(5):
  y = x**2
  y.backward()
  print(x.grad)
  x.grad.zero_()  # whenever u add _ after fn it makes the changes inplace

tensor([6.])
tensor([6.])
tensor([6.])
tensor([6.])
tensor([6.])
