<a href="https://colab.research.google.com/github/VIHAN-droid/AI-ML-PROJECT/blob/main/PYTORCH/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS

In [ ]:
'''
tensors are multi dimensional arrays
0-dim : numbers
1-dim : arrays/collection of nums
2-dim : grayscale image
3-dim : rgb image
4-dim : batches of rbg image
5-dim : video data -> combination of frames
'''

In [1]:
import torch

In [2]:
torch.empty(2,3) # creates an empty(garbage values) tensor of shape -> (2,3)

tensor([[5.2602e+22, 3.3557e-06, 2.1707e-18],
        [4.5447e+30, 7.0062e+22, 2.1715e-18]])

In [3]:
torch.zeros(1,5)

tensor([[0., 0., 0., 0., 0.]])

In [4]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.rand(2,3) # matrix of shape (2,3) with random values between 0 and 1

tensor([[0.6268, 0.3115, 0.5663],
        [0.6079, 0.5990, 0.0798]])

In [7]:
# if u want to use the same values in random
torch.manual_seed(1)
torch.rand(3,4)

tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])

In [9]:
torch.manual_seed(1)
torch.rand(3,4) # same matrix is generated when seed 1 is used

tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]]) # tensor of shape (2,3)
print(x)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [13]:
# can use arange and linspace as well like in numpy
x1 = torch.linspace(1,10,10)
print(x1)

x2 = torch.eye(3) # identity matrix with n=3
print(x2)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [15]:
# create an empty tensor with shape same as x
print(torch.empty_like(x))
# or
print(torch.empty(x.shape))

tensor([[    134693434572160,           490308016,                  32],
        [                 64,              119611, 4189038638018098015]])
tensor([[-5.2560e+01,  4.3945e-41,  2.7760e-21],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])


In [ ]:
# to get the data type use dtype

In [18]:
x = x.to(torch.float32)
x # converted to float

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [22]:
# MATHEMATICAL OPERATION USING SCALARS

# x = tensor([[1, 2, 3],
#          [4, 5, 6]])

print(x+2)

print(x-1)

print(x*3)

print(x/3)

print(x//2)

tensor([[3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 3,  6,  9],
        [12, 15, 18]])
tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])
tensor([[0, 1, 1],
        [2, 2, 3]])


In [45]:
# TENSOR OPERATIONS
a = torch.tensor([[1,2,3],[3,4,5]])
b = torch.tensor([[2,3,4],[5,6,7]])

# SAME SHAPE -> operations are performed on respective elements

print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[ 3,  5,  7],
        [ 8, 10, 12]])
tensor([[-1, -1, -1],
        [-2, -2, -2]])
tensor([[ 2,  6, 12],
        [15, 24, 35]])
tensor([[0.5000, 0.6667, 0.7500],
        [0.6000, 0.6667, 0.7143]])


In [26]:
# abs
c = torch.tensor([[1,-2,3],[-4,-5,-6]])
print(torch.abs(c)) # abs value of each element

tensor([[1, 2, 3],
        [4, 5, 6]])


In [30]:
# round
torch.manual_seed(1)
d = torch.rand(3,4)
print(d)
print((torch.round(d)))

tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[1., 0., 0., 1.],
        [0., 1., 0., 1.],
        [1., 0., 1., 1.]])


In [36]:
# sum
print(torch.sum(d)) # sum of all elements
print(torch.sum(d,dim=0)) # sum along the columns
print(torch.sum(d,dim=1)) # sum along the rows

# mean
print(torch.mean(d)) # mean of all elements, sim. u can finde mean by row or clm by setting dim=0 or 1

# same for std dev. , varn, median , min , max, etc

tensor(6.3270)
tensor([1.3564, 1.5179, 1.4389, 2.0137])
tensor([2.1747, 1.9806, 2.1716])
tensor(0.5272)


In [50]:
# matrix multiplication
print(a)
# b = b.reshape((3,2))
# or
b = torch.transpose(b,0,1)
print(b)

print("\nMatrix Multiplication : \n",torch.matmul(a,b))

tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[2, 5],
        [3, 6],
        [4, 7]])

Matrix Multiplication : 
 tensor([[20, 38],
        [38, 74]])


In [48]:
# DOT PRODUCT
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([4,5,6])

print(torch.dot(v1,v2)) # dot product of vectors/1-d tensor

tensor(32)


In [59]:
# determinant
m = torch.tensor([[1,2,3],[1,1,0],[0,2,1]],dtype=torch.float32)
print(torch.det(m))

tensor(5.)


In [60]:
# same comparison fns like numpy

In [69]:
# sigmoid and softmax fn
print(a)

print(torch.sigmoid(a))

print(torch.softmax(a.to(torch.float32),dim=1)) # calculated dimension wise

# dim = 1 for rows
# dim = 0 for clms

tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[0.7311, 0.8808, 0.9526],
        [0.9526, 0.9820, 0.9933]])
tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


In [76]:
# unsqueeze
c = torch.rand(2,4)
c.unsqueeze(0).shape  # creates a new clm at the index specified

# similarly squeeze removes the clm at the index

torch.Size([1, 2, 4])