<a href="https://colab.research.google.com/github/VIHAN-droid/AI-ML-PROJECT/blob/main/Neural%20Networks/nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch
import torch.nn as nn

class Model(nn.Module):  # inherits nn.Module
  def __init__(self, num_features): # num_features -> number of features
    super().__init__()
    self.sigmoid = nn.Sigmoid()
    self.linear = nn.Linear(num_features, 1)  # no of features and no of outputs  -> a single neuron

  def forward(self,num_features):
    out = self.linear(num_features)
    out = self.sigmoid(out)
    return out

In [13]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)  # simply use Model to call the features no need for Model.forward(features)

tensor([[0.7190],
        [0.6306],
        [0.6508],
        [0.6076],
        [0.6752],
        [0.5520],
        [0.6268],
        [0.6483],
        [0.6651],
        [0.5792]], grad_fn=<SigmoidBackward0>)

In [14]:
model.linear.weight # prints the weight of that neuron

Parameter containing:
tensor([[-0.1474,  0.3121,  0.3976,  0.1667, -0.3555]], requires_grad=True)

In [15]:
model.linear.bias

Parameter containing:
tensor([0.4266], requires_grad=True)

# NEURAL NETWORK

In [ ]:
# plan : 5 input neurons , 1 hidden layer containing 3 neurons (relu) , and final output neuron (sigmoid)

In [18]:
import torch
import torch.nn as nn

class Model(nn.Module):  # inherits nn.Module
  def __init__(self, num_features): # num_features -> number of features
    super().__init__()
    self.sigmoid = nn.Sigmoid()
    self.relu = nn.ReLU()
    self.linear1 = nn.Linear(num_features, 3)  # no of features and no of outputs  -> a single neuron
    self.linear2 = nn.Linear(3,1)

  def forward(self,num_features):
    out = self.linear1(num_features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [19]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.3738],
        [0.4037],
        [0.3547],
        [0.3689],
        [0.3652],
        [0.3980],
        [0.3911],
        [0.3776],
        [0.3595],
        [0.3520]], grad_fn=<SigmoidBackward0>)

In [20]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3217, -0.0061,  0.3192,  0.3625,  0.1348],
        [-0.2433, -0.1500, -0.3951,  0.4189,  0.1428],
        [ 0.0565, -0.4008,  0.0711, -0.0071,  0.0330]], requires_grad=True)

In [22]:
model.linear2.weight

Parameter containing:
tensor([[-0.4515, -0.5694, -0.1902]], requires_grad=True)

In [23]:
model.linear1.bias

Parameter containing:
tensor([-0.2968, -0.1083, -0.4173], requires_grad=True)

In [26]:
!pip install torchinfo

In [27]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# IMPROVED NEURAL NETWORK

In [31]:
# forward fn is redundant
# that's why sequnetial Network is used

In [32]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,num_features):
    out = self.network(num_features)
    return out

In [33]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.3888],
        [0.3985],
        [0.3854],
        [0.3932],
        [0.4026],
        [0.3969],
        [0.3942],
        [0.4063],
        [0.3914],
        [0.4011]], grad_fn=<SigmoidBackward0>)

In [37]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# USING DATA

In [68]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [44]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [45]:
learning_rate = 0.1
epochs = 25

In [66]:
# LOSS FN
loss_function = nn.BCELoss()

In [47]:
model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [43]:
# model params iterate over all the trainable parameters

In [48]:
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1)) # view fn works same as reshape fn

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.867847740650177
Epoch: 2, Loss: 0.6128309369087219
Epoch: 3, Loss: 0.48192206025123596
Epoch: 4, Loss: 0.4064990282058716
Epoch: 5, Loss: 0.3574890196323395
Epoch: 6, Loss: 0.3228521943092346
Epoch: 7, Loss: 0.2968803644180298
Epoch: 8, Loss: 0.2765441834926605
Epoch: 9, Loss: 0.26009097695350647
Epoch: 10, Loss: 0.2464364469051361
Epoch: 11, Loss: 0.23487308621406555
Epoch: 12, Loss: 0.22491881251335144
Epoch: 13, Loss: 0.21623308956623077
Epoch: 14, Loss: 0.20856814086437225
Epoch: 15, Loss: 0.20173895359039307
Epoch: 16, Loss: 0.19560426473617554
Epoch: 17, Loss: 0.19005419313907623
Epoch: 18, Loss: 0.18500174582004547
Epoch: 19, Loss: 0.18037717044353485
Epoch: 20, Loss: 0.17612358927726746
Epoch: 21, Loss: 0.172194242477417
Epoch: 22, Loss: 0.16855023801326752
Epoch: 23, Loss: 0.16515891253948212
Epoch: 24, Loss: 0.16199257969856262
Epoch: 25, Loss: 0.15902763605117798


In [49]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5124653577804565


# USING DATASET AND DATA LOADER

In [50]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [51]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [52]:
from torch.utils.data import Dataset, DataLoader

In [54]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [57]:
dataset = CustomDataset(X,y)

In [58]:
dataset[1]

(tensor([-1.1402, -0.8388]), tensor(0))

In [59]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [64]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)

tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]])
tensor([1, 0])
tensor([[-0.7206, -0.9606],
        [-1.9629, -0.9923]])
tensor([0, 0])
tensor([[-2.8954,  1.9769],
        [ 1.7774,  1.5116]])
tensor([0, 1])
tensor([[ 1.8997,  0.8344],
        [-1.1402, -0.8388]])
tensor([1, 0])
tensor([[-0.9382, -0.5430],
        [ 1.7273, -1.1858]])
tensor([1, 1])


In [69]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [70]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [67]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

learning_rate = 0.1
epochs = 25

model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [71]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:  # using data loader

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.23138652741909027
Epoch: 2, Loss: 0.39962345361709595
Epoch: 3, Loss: 0.08191197365522385
Epoch: 4, Loss: 0.07616198062896729
Epoch: 5, Loss: 0.20192648470401764
Epoch: 6, Loss: 0.05171097069978714
Epoch: 7, Loss: 0.14833010733127594
Epoch: 8, Loss: 0.06774603575468063
Epoch: 9, Loss: 0.024937370792031288
Epoch: 10, Loss: 0.044459518045186996
Epoch: 11, Loss: 0.02803844027221203
Epoch: 12, Loss: 0.027358869090676308
Epoch: 13, Loss: 0.0032660390716046095
Epoch: 14, Loss: 0.03386712819337845
Epoch: 15, Loss: 0.013295295648276806
Epoch: 16, Loss: 0.158213809132576
Epoch: 17, Loss: 0.009312567301094532
Epoch: 18, Loss: 0.03897556662559509
Epoch: 19, Loss: 0.0689634457230568
Epoch: 20, Loss: 0.08398980647325516
Epoch: 21, Loss: 0.005194388329982758
Epoch: 22, Loss: 0.09775925427675247
Epoch: 23, Loss: 0.11873970180749893
Epoch: 24, Loss: 0.032637644559144974
Epoch: 25, Loss: 0.06386034935712814


In [72]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5584795475006104
